# use the shared Yast defaults
inherit_from:
  /usr/share/YaST2/data/devtools/data/rubocop-0.71.0_yast_style.yml

Metrics/LineLength:
  Max: 100

# Offense count: 2
Metrics/AbcSize:
  Max: 26

# Offense count: 4
# Configuration parameters: CountComments.
Metrics/MethodLength:
  Max: 20

# disable block length due to rspec DSL which is build from blocks
Metrics/BlockLength:
  Enabled: false
